title: YORU Dev Log
description: YORU의 개발/게임 기록 블로그
lang: ko
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

future: true
timezone: Asia/Seoul

repository: dippydro22/dippydro22.github.io

url: "https://dippydro22.github.io"
baseurl: ""
